compileJava.options.encoding = 'UTF-8'
compileTestJava.options.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

dependencies {
  api "com.badlogicgames.gdx:gdx:$gdxVersion"

  if(enableGraalNative == 'true') {
    implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
  }
}

jar {
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

// ========== TAREAS PARA EJECUTAR SERVIDOR Y CLIENTE ==========
task runServidor(type: JavaExec) {
  classpath = sourceSets.main.runtimeClasspath
  mainClass = 'com.proyecto.juegoudp.test.TestServidor'
}
task runCliente(type: JavaExec) {
  classpath = sourceSets.main.runtimeClasspath
  mainClass = 'com.proyecto.juegoudp.test.TestCliente'
}
task runServidorJuego(type: JavaExec) {
  classpath = sourceSets.main.runtimeClasspath
  mainClass = 'com.proyecto.juegoudp.test.TestJuegoRed'
}
task runClienteJuego(type: JavaExec) {
  classpath = sourceSets.main.runtimeClasspath
  mainClass = 'com.proyecto.juegoudp.test.TestJuegoRed'
  args = ['cliente', 'MiNombre']
}